stages:
  - static
  - tests
  - test
  - docker
linters:
  stage: static
  image: python:3.11
  script:
    - python -m venv --prompt ci_venv venv
    - source venv/bin/activate
    - pip install -U pip setuptools wheel
    - python -V
    - pip install -e ".[dev]"
    - pre-commit run --all-files --show-diff-on-failure
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pytest:
  stage: tests
  image: python:3.11
  coverage: '/^TOTAL.+?(\d+\%)$/'
  script:
    - python -m venv --prompt ci_venv venv
    - source venv/bin/activate
    - pip install -U pip setuptools wheel
    - python -V
    - pip install -e ".[dev]"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
docker:
  stage: docker
  image: docker:latest
  tags:
    - docker-privileged-xl
  services:
    - name: docker:dind
      alias: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -f ./Dockerfile.client .
    - docker push $CI_REGISTRY_IMAGE/server:$CI_COMMIT_TAG

include:
  - template: Jobs/SAST.gitlab-ci.yml #https://gitlab.cern.ch/help/user/application_security/sast/index
  - template: Jobs/Secret-Detection.gitlab-ci.yml #https://gitlab.cern.ch/help/user/application_security/secret_detection/index
  - template: Security/Dependency-Scanning.gitlab-ci.yml #https://gitlab.cern.ch/help/user/application_security/dependency_scanning/index
